{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/profile","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/profile (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213689CA8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"},"timestamp":"2024-10-07 23:38:44,095+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:161] fyersModel","message":{"API":"/funds","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /api/v3/funds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213689EA3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"},"timestamp":"2024-10-07 23:38:44,098+0530","service":"FyersAPI"}
